import { DiffHunk } from '@/lib/types';

/**
 * Unified Diff Parser & Reconstitution Engine
 * Extracted from open-source diff viewer reference patterns.
 */

/**
 * Computes a real SHA-256 digest (Web Crypto) over the accepted hunk set,
 * truncated to 16 hex chars for display. Used for safe barrier verification.
 */
export async function computePatchHash(hunks: DiffHunk[]): Promise<string> {
  const content = hunks
    .map(h => `${h.id}:${h.file}:${h.status}:${h.oldStart}-${h.newStart}`)
    .join('|');
  const data = new TextEncoder().encode(content);
  const digest = await crypto.subtle.digest('SHA-256', data);
  return Array.from(new Uint8Array(digest))
    .map(b => b.toString(16).padStart(2, '0'))
    .join('')
    .slice(0, 16);
}

/**
 * Generates interactive DiffHunks from code strings or unified diff format
 */
export function parseCodeToHunks(
  fileName: string,
  initialCode: string,
  modifiedCode?: string
): DiffHunk[] {
  if (modifiedCode && modifiedCode !== initialCode) {
    const initLines = initialCode.split('\n');
    const modLines = modifiedCode.split('\n');

    return [
      {
        id: `hunk-${fileName.replace(/[^a-zA-Z0-9]/g, '_')}-1`,
        file: fileName,
        oldStart: 1,
        oldLines: Math.max(1, initLines.length),
        newStart: 1,
        newLines: Math.max(1, modLines.length),
        header: `@@ -1,${initLines.length} +1,${modLines.length} @@`,
        lines: [
          ...initLines.map(l => ({ type: 'deletion' as const, content: l })),
          ...modLines.map(l => ({ type: 'addition' as const, content: l })),
        ],
        status: 'pending',
        explanation: `Surgical patch for ${fileName} generated by Multi-Agent Sweep`,
      },
    ];
  }

  return parseUnifiedDiffToHunks(fileName, initialCode);
}

/**
 * Reconciles original code with accepted diff hunks in descending order
 * to prevent line index offset drift.
 */
export function reconcileApprovedHunks(
  originalCode: string,
  hunks: DiffHunk[]
): string {
  const lines = originalCode.split('\n');
  
  // Filter accepted hunks and sort by descending start line to preserve index stability
  const acceptedHunks = hunks
    .filter(h => h.status === 'accepted')
    .sort((a, b) => b.oldStart - a.oldStart);

  if (acceptedHunks.length === 0) return originalCode;

  const updatedLines = [...lines];

  for (const hunk of acceptedHunks) {
    const removeCount = hunk.oldLines;
    const replacementLines = hunk.lines
      .filter(l => l.type === 'addition' || l.type === 'context')
      .map(l => l.content);

    const targetIndex = Math.max(0, hunk.oldStart - 1);
    updatedLines.splice(targetIndex, removeCount, ...replacementLines);
  }

  return updatedLines.join('\n');
}

/**
 * Parses raw unified diff string into discrete interactive DiffHunk structures
 */
export function parseUnifiedDiffToHunks(
  fileName: string,
  rawDiff: string
): DiffHunk[] {
  const lines = rawDiff.split('\n');
  const hunks: DiffHunk[] = [];
  let currentHunk: Partial<DiffHunk> | null = null;
  let hunkCounter = 1;

  for (const line of lines) {
    if (line.startsWith('@@')) {
      if (currentHunk && currentHunk.lines) {
        hunks.push(currentHunk as DiffHunk);
      }

      const match = line.match(/@@ -(\d+),?(\d+)? \+(\d+),?(\d+)? @@/);
      const oldStart = match ? parseInt(match[1], 10) : 1;
      const oldLines = match && match[2] ? parseInt(match[2], 10) : 1;
      const newStart = match && match[3] ? parseInt(match[3], 10) : 1;
      const newLines = match && match[4] ? parseInt(match[4], 10) : 1;

      currentHunk = {
        id: `hunk-${fileName.replace(/[^a-zA-Z0-9]/g, '_')}-${hunkCounter++}`,
        file: fileName,
        header: line,
        oldStart,
        oldLines,
        newStart,
        newLines,
        lines: [],
        status: 'pending',
        explanation: 'Surgical AST diff hunk auto-generated by PSMAS Multi-Agent Pipeline',
      };
    } else if (currentHunk && currentHunk.lines) {
      if (line.startsWith('+') && !line.startsWith('+++')) {
        currentHunk.lines.push({
          type: 'addition',
          content: line.substring(1),
        });
      } else if (line.startsWith('-') && !line.startsWith('---')) {
        currentHunk.lines.push({
          type: 'deletion',
          content: line.substring(1),
        });
      } else {
        currentHunk.lines.push({
          type: 'context',
          content: line.startsWith(' ') ? line.substring(1) : line,
        });
      }
    }
  }

  if (currentHunk && currentHunk.lines) {
    hunks.push(currentHunk as DiffHunk);
  }

  return hunks;
}
